vim.g.coc_global_extensions = {
	'coc-css',
	'coc-eslint',
	'coc-html',
	'coc-json',
	'coc-xml',
	'coc-prettier',
	'coc-git',
	'coc-tsserver',
	'coc-ember',
	'coc-graphql',
	'coc-highlight',
	'coc-python',
	'coc-prettier',
}
